### ISSUE TITLE
v5/fileresources/type/ liefert eine UnsupportedOperationException

### ISSUE THREAD

**Issue by clorenz** [dbmdz/cudami#1670]
Getestet mit type `image`. Ergebnis ist Status 500 mit Exception
```
j.l.UnsupportedOperationException: null\n\tat j.u.AbstractMap.put(AbstractMap.java:209)
  at d.d.c.s.b.i.j.JdbiRepositoryImpl.getWhereClause(JdbiRepositoryImpl.java:184)
  at d.d.c.s.b.i.j.JdbiRepositoryImpl.getFilterClauses(JdbiRepositoryImpl.java:72)
  at d.d.c.s.b.i.j.JdbiRepositoryImpl.addFiltering(JdbiRepositoryImpl.java:44)
  at d.d.c.s.b.i.j.JdbiRepositoryImpl.addFiltering(JdbiRepositoryImpl.java:36)
  at d.d.c.s.b.i.j.i.IdentifiableRepositoryImpl.find(IdentifiableRepositoryImpl.java:408)
  at d.d.c.s.b.i.j.i.IdentifiableRepositoryImpl.find(IdentifiableRepositoryImpl.java:395)
    ... 5 frames excluded
  at o.s.d.s.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
    ... 121 frames truncated
```

**Comment by morpheus-87** [comment]
Funktioniert in der aktuellen Version auf `main`.
